default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: <%= ENV['DATABASE_NAME'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  host: <%= Rails.application.credentials.database[:host] %>
  username: <%= Rails.application.credentials.database[:user] %>
  password: <%= Rails.application.credentials.database[:password] %>
  database: <%= Rails.application.credentials.database[:name] %>
