# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: app/proto/category.proto for package 'plan'

require 'grpc'

module Plan
  module Category
    class Service
      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'plan.Category'

      rpc :GetCategories, ::Google::Protobuf::Empty, ::Plan::GetCategoriesResp
    end

    Stub = Service.rpc_stub_class
  end
end
